apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blue-admin
  namespace: blue
subjects:
  - kind: Group
    name: "twks-cohort/blue"
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: blue-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  name: blue-admin
  namespace: blue
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - '*'
---
